---
title: "methods"
author: "Andrea Seisler"
date: "`r Sys.time()`"
output: html_document
---

What are the methods to be used when sampling and categorizing papers?

Keywords: developmental psychology, behavioural research

Which Journals are relevant? Check out here: https://www.scimagojr.com/journalrank.php?category=3204

  - [**Child Development**](https://onlinelibrary.wiley.com/journal/14678624)
  - [Developmental Psychology](http://www.apa.org/pubs/journals/dev/index.aspx)
  - [**Developmental Science**](https://onlinelibrary.wiley.com/journal/14677687)
  - [Journal of Experimental Child Psychology (JECP)](https://www.journals.elsevier.com/journal-of-experimental-child-psychology)
  - [**Infancy**](https://onlinelibrary.wiley.com/journal/15327078)
  - [Infant Behavior and Development](https://www.journals.elsevier.com/infant-behavior-and-development)
  
  - [Developmental Review](https://www.sciencedirect.com/journal/developmental-review)


## How to code a paper

- Log into the Gilmore Lab Chrome Account
- Open Paperpile in a new tab

### Open the journal

#### On Campus
- Open the journal website in another tab (On Campus)

#### Off Campus
- In a new tab, go to the [PSU Library](https://libraries.psu.edu/) site
- Choose the 'E-Journals' tab of the search box
- Type the name of the Journal in the box and press the search button
- log in with your psu credentials
- Click on the link to the journal
- A new tab will open
- Click on the issue
- click on the journal article
- click on the link to the individual paper
- Follow the 'In the Journal Website Tab' instructions below
- Open the .pdf file
- Download the .pdf
- Upload the .pdf into the paperpile citation manually


#### In the Journal Website Tab
- Click on the link to the journal article
- Choose the paperpile icon from the upper right hand cornder of the chrome window
- Select 'Add to Paperpile'
- Select 'View in Paperpile'

#### In the Paperpile Tab
- Choose Cite > Citation from the menu bar at the top of the screen to copy the citation

### In journal.Rmd in RStudio
- Paste the citation (CMD+P)

### In the Paperpile Tab
- click on 'View PDF' for the journal article you want to read
- This .pdf will open in a new tab

### Read the journal article and copy/paste relevant parts of the methods section that describe any measures/tasks used for the study to the journal.Rmd file.

### Close the .pdf of the journal article

### Go back to 'In the Journal Article Tab'








Sample papers from: XXXX - Today's Date

Data Collection Methods - Types of Tasks
- Contexts
  - lab
  - home
  - school
- Displays, environments
  - computer
  - lab task
- Measures
  - video, eye tracking, keyboard, mouse, EEG, survey, observational ratings
- surveys (administered in various forms)
  - interview
  - paper
  - computer
- imaging
  - EEG
  - MRI
- response type
  - mouse
  - button presses (e.g. keyboard, button box, game controller)
  - verbal response
  - eye gaze
- video


